// Code generated by LanguageTool

export function add(x: number, y: number): number {
  return x + y;
}

console.log(add(3, 5)); // Output: 8

function subtract(x: number, y: number): number {
  return x - y;
}

console.log(subtract(10, 4)); // Output: 6
